CREATE DATABASE IF NOT EXISTS farminvest;
USE farminvest;

CREATE TABLE investments (
  id INT PRIMARY KEY AUTO_INCREMENT,
  farmer_name VARCHAR(100) NOT NULL,
  amount DECIMAL(10, 2) NOT NULL,
  crop VARCHAR(50) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);